title = "路遥柯"
baseURL = "https://cycleke.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "路遥柯"
  description = "路漫漫其修远兮，吾将上下而求索"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    themeAuthor = "Olivier Roques"
    themeUrl = "https://github.com/ojroques/hugo-researcher"
    since = "2021"
    copyright = "路遥柯"
    beian = "蜀ICP备2021020864号-1"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "'IBM Plex Serif', 'Noto Serif SC', 'Source Han Serif SC', 'Source Han Serif CN', 'Source Han Serif TC', 'Source Han Serif TW', 'Source Han Serif', serif !default"
    titleFont = "'Ma Shan Zheng', serif !default"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

  [[params.socialIcons]]
    icon = "fas fa-blog"
    title = "随笔"
    url = "https://blog.cycleke.com"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/cycleke/"
  [[params.socialIcons]]
    icon = "fab fa-qq"
    title = "QQ"
    url = "http://wpa.qq.com/msgrd?v=3&uin=1352216033&site=qq&menu=yes"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "邮箱"
    url = "mailto:cycleke@gmail.com"
  [[params.socialIcons]]
    icon = "fab fa-telegram"
    title = "Telegram"
    url = "tg://resolve?domain=cycleke"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "关于我"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "随笔"
    url = "https://blog.cycleke.com/"
    weight = 2
  [[menu.main]]
    name = "其他链接"
    url = "/links"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
